notification
notifyFailure: arg1
	self
		inform: 'A problem has occurred while sending the report: ' , arg1